baseurl = "https://identity2.github.io/"
languageCode = "en-us"
Title = "New Tab"
theme = "shineright_theme"
# Copyright notice. This is displayer in the footer.
copyright = ""

[markup.goldmark.renderer]
unsafe = true

[params]
  paginate = 10
  # Google Analytics API key.
  ga_api_key = "UA-109245777-1"
  author = ""
  authorwebsite = "identity2.github.io"
  avatar = ""
  contact = "mailto:yuchao20040229@gmail.com"
  bio = ""
  logo = ""
  title_image = "/title-image.png"
  fail_image = "/about/avatar-banner.png"
  favicon = "/favicon.ico"